<?php

namespace AppBundle\Repository;

/**
 * BrandTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
