<?php

namespace AppBundle\Repository;

/**
 * SuffixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuffixRepository extends \Doctrine\ORM\EntityRepository
{
}
